### ISSUE TITLE
worker 0:	error connecting to relay node 0: Connection refused

### ISSUE THREAD

**Issue by lihuahua123** [libertyeagle/JellyBean#1]
example/config.json为
```
 "request_rate": 40.0,
    "dataset_path": "/home/server/fastT/JellyBean/VQA/data/VQA_Workflow_Datasets",
    "logging_dir": "~/VQAWorkflowLogging",
    "pipeline_specs": {
        "pipeline_0": {
            "worker_addrs": ["192.168.249.122:5000"],
            "relay_addrs": ["192.168.249.122:7000"],
            "model_assignments": {},
            "device_placements": {}
        },
....
```
在192.168.249.122上运行 `cargo run --release --bin workflow -- -c examples/config.json -p 0 -i 0` 但是报错
worker 0:	error connecting to relay node 0: Connection refused
端口没有被占用，请问要怎么解决呢，谢谢！

**Comment by libertyeagle** [comment]
请问你有已经运行了所有pipeline的所有worker&relay吗？relay进程要先和input/output pipeline的relay建立连接，要所有pipeline都运行之后worker才算能完成初始化

**Comment by lihuahua123** [comment]
> 请问你有已经运行了所有pipeline的所有worker&relay吗？relay进程要先和input/output pipeline的relay建立连接，要所有pipeline都运行之后worker才算能完成初始化

确实可以，要在所有的节点上都运行，谢谢您了！
